#!/bin/bash
# Archive unused files from src/ directory
# Generated by: analyze_src_cleanup.py

set -e

cd /Users/marghubakhtar/Documents/social_support_agentic_ai

# Create archive directory
mkdir -p src_archive

echo "========================================"
echo "ARCHIVING UNUSED src/ FILES"
echo "========================================"
echo ""
echo "This will move 25 unused files to src_archive/"
echo ""
read -p "Continue? (y/n) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    echo "Cancelled."
    exit 0
fi

echo ""
echo "Moving unused files..."


# Archive from src/agents/
mkdir -p src_archive/src/agents/
mv "src/agents/recommendation_agent_old.py" "src_archive/src/agents/recommendation_agent_old.py"
mv "src/agents/validation_agent_old.py" "src_archive/src/agents/validation_agent_old.py"

# Archive from src/core/
mkdir -p src_archive/src/core/
mv "src/core/base_agent.py" "src_archive/src/core/base_agent.py"

# Archive from src/database/
mkdir -p src_archive/src/database/
mv "src/database/__init__.py" "src_archive/src/database/__init__.py"
mv "src/database/chromadb_manager.py" "src_archive/src/database/chromadb_manager.py"
mv "src/database/database_manager.py" "src_archive/src/database/database_manager.py"
mv "src/database/neo4j_manager.py" "src_archive/src/database/neo4j_manager.py"
mv "src/database/sqlite_client.py" "src_archive/src/database/sqlite_client.py"

# Archive from src/databases/
mkdir -p src_archive/src/databases/
mv "src/databases/database_manager.py" "src_archive/src/databases/database_manager.py"
mv "src/databases/neo4j_manager.py" "src_archive/src/databases/neo4j_manager.py"
mv "src/databases/unified_database_manager.py" "src_archive/src/databases/unified_database_manager.py"
mv "src/databases/unified_db.py" "src_archive/src/databases/unified_db.py"

# Archive from src/ml/
mkdir -p src_archive/src/ml/
mv "src/ml/explainability.py" "src_archive/src/ml/explainability.py"
mv "src/ml/ml_pipeline.py" "src_archive/src/ml/ml_pipeline.py"
mv "src/ml/synthetic_data_generator.py" "src_archive/src/ml/synthetic_data_generator.py"
mv "src/ml/train_model.py" "src_archive/src/ml/train_model.py"

# Archive from src/observability/
mkdir -p src_archive/src/observability/
mv "src/observability/langfuse_tracker.py" "src_archive/src/observability/langfuse_tracker.py"

# Archive from src/rag/
mkdir -p src_archive/src/rag/
mv "src/rag/__init__.py" "src_archive/src/rag/__init__.py"
mv "src/rag/production_rag.py" "src_archive/src/rag/production_rag.py"

# Archive from src/services/
mkdir -p src_archive/src/services/
mv "src/services/document_extractor.py" "src_archive/src/services/document_extractor.py"
mv "src/services/excel_parser.py" "src_archive/src/services/excel_parser.py"
mv "src/services/llm_service.py" "src_archive/src/services/llm_service.py"
mv "src/services/ocr_service.py" "src_archive/src/services/ocr_service.py"
mv "src/services/rag_engine.py" "src_archive/src/services/rag_engine.py"
mv "src/services/resume_parser.py" "src_archive/src/services/resume_parser.py"

echo ""
echo "========================================"
echo "ARCHIVE COMPLETE"
echo "========================================"
echo ""
echo "Archived files are in: src_archive/"
echo ""
echo "To restore a file:"
echo "  mv src_archive/path/to/file.py src/path/to/file.py"
echo ""
echo "To permanently delete archives (after verification):"
echo "  rm -rf src_archive/"
echo ""
