#!/bin/bash
# Automated Project Cleanup Script
# Generated by analyze_project_cleanup.py

set -e  # Exit on error

echo "========================================"
echo "PROJECT CLEANUP SCRIPT"
echo "========================================"
echo ""
echo "This script will:"
echo "  1. Archive phase documentation"
echo "  2. Archive old test files"
echo "  3. Remove duplicate database managers"
echo "  4. Clean up unused Python files"
echo ""
read -p "Continue? (y/n) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 0
fi

cd /Users/marghubakhtar/Documents/social_support_agentic_ai

# Create archive directories
mkdir -p docs/archive/phases
mkdir -p docs/archive/status
mkdir -p docs/archive/guides
mkdir -p tests/archive

echo ""
echo "1. Archiving phase documentation..."
mv "PHASE10_COMPLETE.md" docs/archive/phases/ 2>/dev/null || true
mv "PHASE1_COMPLETE.md" docs/archive/phases/ 2>/dev/null || true
mv "PHASE1_DATA_PLAN.md" docs/archive/phases/ 2>/dev/null || true
mv "PHASE2_COMPLETE.md" docs/archive/phases/ 2>/dev/null || true
mv "PHASE2_EXTRACTION_COMPLETE.md" docs/archive/phases/ 2>/dev/null || true
mv "PHASE2_OCR_OPTIMIZATION.md" docs/archive/phases/ 2>/dev/null || true
mv "PHASE2_RESULTS.md" docs/archive/phases/ 2>/dev/null || true
mv "PHASE3_CHECKLIST.md" docs/archive/phases/ 2>/dev/null || true
mv "PHASE3_COMPLETE.md" docs/archive/phases/ 2>/dev/null || true
mv "PHASE3_NEXT_STEPS.md" docs/archive/phases/ 2>/dev/null || true
mv "PHASE3_OPTION_A_COMPLETE.md" docs/archive/phases/ 2>/dev/null || true
mv "PHASE3_TEST_SUMMARY.md" docs/archive/phases/ 2>/dev/null || true
mv "PHASE3_VALIDATION_ANALYSIS.md" docs/archive/phases/ 2>/dev/null || true
mv "PHASE5_COMPLETE.md" docs/archive/phases/ 2>/dev/null || true
mv "PHASE6_DATABASE_ARCHITECTURE.md" docs/archive/phases/ 2>/dev/null || true
mv "PHASE6_IMPLEMENTATION.md" docs/archive/phases/ 2>/dev/null || true
mv "PHASE7_COMPLETE.md" docs/archive/phases/ 2>/dev/null || true
mv "PHASE8_COMPLETE.md" docs/archive/phases/ 2>/dev/null || true
mv "PHASE8_QUICK_REFERENCE.md" docs/archive/phases/ 2>/dev/null || true
mv "PHASE8_VERIFICATION_REPORT.md" docs/archive/phases/ 2>/dev/null || true
mv "PHASE9_ASSESSMENT.md" docs/archive/phases/ 2>/dev/null || true
mv "PHASE9_COMPLETION_REPORT.md" docs/archive/phases/ 2>/dev/null || true
mv "PHASE9_DELIVERABLES_SUMMARY.md" docs/archive/phases/ 2>/dev/null || true
mv "PHASE9_QUICK_REFERENCE.md" docs/archive/phases/ 2>/dev/null || true
mv "PROJECT_STATUS_PHASE5.md" docs/archive/phases/ 2>/dev/null || true

echo "   ✓ Phase docs archived"

echo ""
echo "2. Archiving status reports..."
mv "API_FIXES_COMPLETE.md" docs/archive/status/ 2>/dev/null || true
mv "CHROMADB_PRODUCTION_COMPLETE.md" docs/archive/status/ 2>/dev/null || true
mv "FAANG_GRADE_RAG_COMPLETE.md" docs/archive/status/ 2>/dev/null || true
mv "MAIN_API_INTEGRATION_COMPLETE.md" docs/archive/status/ 2>/dev/null || true
mv "PHASE10_COMPLETE.md" docs/archive/status/ 2>/dev/null || true
mv "PHASE1_COMPLETE.md" docs/archive/status/ 2>/dev/null || true
mv "PHASE2_COMPLETE.md" docs/archive/status/ 2>/dev/null || true
mv "PHASE2_EXTRACTION_COMPLETE.md" docs/archive/status/ 2>/dev/null || true
mv "PHASE3_COMPLETE.md" docs/archive/status/ 2>/dev/null || true
mv "PHASE3_OPTION_A_COMPLETE.md" docs/archive/status/ 2>/dev/null || true
mv "PHASE5_COMPLETE.md" docs/archive/status/ 2>/dev/null || true
mv "PHASE7_COMPLETE.md" docs/archive/status/ 2>/dev/null || true
mv "PHASE8_COMPLETE.md" docs/archive/status/ 2>/dev/null || true
mv "PROJECT_STATUS.md" docs/archive/status/ 2>/dev/null || true
mv "PROJECT_STATUS_PHASE5.md" docs/archive/status/ 2>/dev/null || true
mv "README_COMPLETE_GUIDE.md" docs/archive/status/ 2>/dev/null || true
mv "REAL_SOLUTION_COMPLETE.md" docs/archive/status/ 2>/dev/null || true

echo "   ✓ Status reports archived"

echo ""
echo "3. Archiving old test files (keeping latest)..."
mv "load_test.py" tests/archive/ 2>/dev/null || true
mv "load_test.py" tests/archive/ 2>/dev/null || true
mv "phase6_fast_test.py" tests/archive/ 2>/dev/null || true
mv "phase6_fast_test.py" tests/archive/ 2>/dev/null || true
mv "phase7_integration_test.py" tests/archive/ 2>/dev/null || true
mv "phase7_integration_test.py" tests/archive/ 2>/dev/null || true
mv "phase7_lightweight_test.py" tests/archive/ 2>/dev/null || true
mv "phase7_lightweight_test.py" tests/archive/ 2>/dev/null || true
mv "phase8_governance_test.py" tests/archive/ 2>/dev/null || true
mv "phase8_governance_test.py" tests/archive/ 2>/dev/null || true
mv "phase8_verification_test.py" tests/archive/ 2>/dev/null || true
mv "phase8_verification_test.py" tests/archive/ 2>/dev/null || true
mv "phase9_fastapi_test.py" tests/archive/ 2>/dev/null || true
mv "phase9_fastapi_test.py" tests/archive/ 2>/dev/null || true
mv "rigorous_test.py" tests/archive/ 2>/dev/null || true
mv "rigorous_test.py" tests/archive/ 2>/dev/null || true
mv "test.py" tests/archive/ 2>/dev/null || true
mv "test.py" tests/archive/ 2>/dev/null || true
mv "test_agents.py" tests/archive/ 2>/dev/null || true
mv "test_all_components.py" tests/archive/ 2>/dev/null || true
mv "test_api.py" tests/archive/ 2>/dev/null || true
mv "test_api_flow.py" tests/archive/ 2>/dev/null || true
mv "test_app_967DFD01.py" tests/archive/ 2>/dev/null || true
mv "test_assets_extraction.py" tests/archive/ 2>/dev/null || true
mv "test_bug_fixes.py" tests/archive/ 2>/dev/null || true
mv "test_case_fix.py" tests/archive/ 2>/dev/null || true
mv "test_complete_pipeline.py" tests/archive/ 2>/dev/null || true
mv "test_comprehensive_extraction.py" tests/archive/ 2>/dev/null || true
mv "test_comprehensive_fix.py" tests/archive/ 2>/dev/null || true
mv "test_data_generation.py" tests/archive/ 2>/dev/null || true
mv "test_database.py" tests/archive/ 2>/dev/null || true
mv "test_database_storage_fix.py" tests/archive/ 2>/dev/null || true
mv "test_db_queries.py" tests/archive/ 2>/dev/null || true
mv "test_decision.py" tests/archive/ 2>/dev/null || true
mv "test_extraction.py" tests/archive/ 2>/dev/null || true
mv "test_faang_rag.py" tests/archive/ 2>/dev/null || true

echo "   ✓ Old tests archived"

echo ""
echo "4. Removing duplicate database managers..."
rm -f src/databases/sqlite_manager_old.py
rm -f src/databases/tinydb_manager_old.py

echo "   ✓ Old database managers removed"

echo ""
echo "========================================"
echo "CLEANUP COMPLETE"
echo "========================================"
echo ""
echo "Summary:"
echo "  - Moved phase docs to docs/archive/phases/"
echo "  - Moved status reports to docs/archive/status/"
echo "  - Moved old tests to tests/archive/"
echo "  - Removed duplicate database managers"
echo ""
echo "Next steps:"
echo "  1. Review archived files"
echo "  2. Delete archives after verification"
echo "  3. Commit changes to git"
